# Generated by Django 4.1.4 on 2023-05-07 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='upload_path')),
                ('ref_id', models.CharField(default='62baff5f84', max_length=10, unique=True)),
                ('file', models.CharField(default='', max_length=255)),
                ('expiration_time', models.DateTimeField(default=datetime.datetime(2023, 5, 7, 4, 54, 57, 726680, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
