# Generated by Django 4.1.4 on 2023-05-07 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file',
        ),
        migrations.AlterField(
            model_name='files',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 8, 0, 42, 28922, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='files',
            name='ref_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterModelTable(
            name='files',
            table='userdata',
        ),
    ]
