# Generated by Django 4.1.4 on 2023-05-07 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_files_file_alter_files_expiration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 8, 1, 57, 800860, tzinfo=datetime.timezone.utc)),
        ),
    ]
