# Generated by Django 4.1.4 on 2023-05-07 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_files_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 9, 4, 28, 539073, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='files',
            name='ref_id',
            field=models.CharField(default='72f8003a4e', max_length=10, unique=True),
        ),
    ]
