# Generated by Django 4.1.4 on 2023-05-07 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_files_expiration_time_alter_files_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 9, 14, 20, 284185, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='files',
            name='ref_id',
            field=models.CharField(default='0909a230c1', max_length=10, unique=True),
        ),
    ]
