# Generated by Django 4.1.4 on 2023-05-07 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_files_expiration_time_alter_files_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 12, 51, 25, 799150, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='files',
            name='ref_id',
            field=models.CharField(default='8060beab2c', max_length=10, unique=True),
        ),
    ]
